# This Week’s Overview

This week we're going to apply a number of the concepts covered in class in order to read a remote CSV file, turn it into data, and then perform some simple analyses on it. We're going to first do it 'by hand' (building the tools we need) and then using the 'pandas' package that gives us a very different way to do things.

## Learning Outcomes

By the end of this practical you should:
- Have read a remote data file
- Written a function to derive some statistics
- Have imported a package
- Have made use of methods

# Taking a Second to Think

To a computer, reading data from a remote location (e.g. a web site halfway around the world) is not really any different from reading one that's sitting on your desktop, you just need to make set it up a bit differently and, in Python, make use of a different _package_. In all cases – local and remote – Python gives you a 'filehandle' that supports certain operations like 'open a filehandle', 'read a line', 'close a filehandle'. It's called a filehandle because it's something that gives you a 'grip' on a file-like object.

I also want you to understand how we're approach the problem set out above: we want to read a remote file (i.e. a text file halfway round the planet), turn it into a local data structure (i.e a list or a dictionary), and then perform operations on it using functions (e.g. calculate the mean, find the easternmost city, etc.).

_**But**_, we _don't_ try to do all of this at once by writing a whole lot of code and the hoping for the best; when you're tackling a problem like this you break it down into separate, simpler steps, and then tick them off one by one. So first we'll get Python _reading_ remote data, then we'll _convert_ text into data, and finally we'll _analyse_ the data using functions.

_**Note**_: you might also find it helpful to take a close look at the URL that we are reading by pasting this link into a web browser: http://www.reades.com/CitiesWithWikipediaData-simple.csv. 

# Step 1: Reading a Remote File

So, as I said, we are going to parse a data file hosted on a remote web site. This is just the first step: we are going to build from this first step towards more substantial exercises and, eventually, you could easily request Megabytes of data in real-time according to flexibly-specified parameters!

You'll probably need to do a quick Google in order to make sense of what you're about to do; I'd suggest "`read remote CSV file Python urllib2`".

In [7]:
import urllib2

help(urllib2.urlopen)

url = "http://www.reades.com/CitiesWithWikipediaData-simple.csv"
print("URL: " + url + ".\n")

response = urllib2.urlopen(url) # ???
for line in response: # ???
    print line.rstrip()

Help on function urlopen in module urllib2:

urlopen(url, data=None, timeout=<object object>, cafile=None, capath=None, cadefault=False, context=None)

URL: http://www.reades.com/CitiesWithWikipediaData-simple.csv.

id,Name,Rank,Longitude,Latitude,Population
1,Greater London,1,-18162.92767,6711153.709,9787426
2,Greater Manchester,2,-251761.802,7073067.458,2553379
3,West Midlands,3,-210635.2396,6878950.083,2440986
4,West Yorkshire,4,-185959.3022,7145450.207,1777934
5,Glasgow,5,-473845.2389,7538620.144,1209143
6,Liverpool,6,-340595.1768,7063197.083,864122
7,South Hampshire,7,-174443.8647,6589419.084,855569
8,Tyneside,8,-187604.3647,7356018.207,774891
9,Nottingham,9,-131672.2399,6979298.895,729977
10,Sheffield,10,-163545.3257,7055177.403,685368


If you've managed to get the code above to run and have received 11 rows of text in response to your `urlopen` query then, congratulations, You've now read a text file sitting on a server in, I think, Alberta, Canada and Python _didn't care_. 

The last row should be `10,Sheffield,10,-163545.3257,7055177.403,685368`.

### URLLIB2

In this particular case, I 'gave' you the fact that you'd need to make use of the `urllib2` package in order to read the file. But you could almost certainly have Googled this for yourself using something like 'Python read file on server'...

Urllib2 is a very useful library, but compared to pandas (which we'll see later), it's pretty simple since it just sends a 'request' to a web site and 'reads' the results. You can also do things like submit a form (e.g. you could submit hundreds of applications for a free TV if someone ran a competition... that's why they have 'captchas' now).

Anyway, that's some background, let's move on to step 2! 

## Step 2: Turning Text into Data

We now need to work on turning that text into useful data. You'll notice that we are dealing with a _CSV_ (Comma-Separated Value) file and that the format is quite simple since none of the rows have fields that contain commas. So to turn this into data we just need to _split_ the row on commas.

In the code below, `dir('string')` lists the available methods for strings. Methods that start and end with `__` are generally considered private, so you can skip over these and focus on the ones further down that are designed to be useful to programmers. Can you spot the method that is most likely to be useful?

In [1]:
dir('string')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_formatter_field_name_split',
 '_formatter_parser',
 'capitalize',
 'center',
 'count',
 'decode',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'index',
 'isalnum',
 'isalpha',
 'isdigit',
 'islower',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

Now that you've found the method, why not use the `help` function to figure out how to make use of it?

In [3]:
help('string'.split) #???

Help on built-in function split:

split(...)
    S.split([sep [,maxsplit]]) -> list of strings
    
    Return a list of the words in the string S, using sep as the
    delimiter string.  If maxsplit is given, at most maxsplit
    splits are done. If sep is not specified or is None, any
    whitespace string is a separator and empty strings are removed
    from the result.



OK, so you've tracked down the way to split a string using a delimiter. Let's test it using our sample string to make sure it works the way we think it does.

In [6]:
test = "10,Sheffield,10,-163545.3257,7055177.403,685368".split(",") #???
print test

['10', 'Sheffield', '10', '-163545.3257', '7055177.403', '685368']


Cool! Now that you've figured out how to make use of the appropriate method using `help` and a simple test, it's time to revise the code above so that it turns the remote file into data. You can hopefully see how we're breaking a complex problem down into a set of _increments_, each of which is a bit easier to write and understand. 

Now, remember that ultimately we want to make use of the data in this file, so simply printing it back out ins't particularly helpful. What we really want to do is stash the data we've read in some kind of _data structure_ that resembles the CSV file but is easier and faster for the computer to navigate.

We need:
1. To keep the rows in order
2. To keep the columns in order

With what we've covered in previous sessions and what we've covered in class, what approach might allow us to do this? _Hint:_ is it likely to be a dictionary? 

In [7]:
import urllib2

url = "http://www.reades.com/CitiesWithWikipediaData-simple.csv"

cityData = [] # Somewhere to store the data

response = urllib2.urlopen(url) 
for line in response: 
    cityData.append( line.rstrip().split(",") ) # ???

print cityData # Check it worked!

[['id', 'Name', 'Rank', 'Longitude', 'Latitude', 'Population'], ['1', 'Greater London', '1', '-18162.92767', '6711153.709', '9787426'], ['2', 'Greater Manchester', '2', '-251761.802', '7073067.458', '2553379'], ['3', 'West Midlands', '3', '-210635.2396', '6878950.083', '2440986'], ['4', 'West Yorkshire', '4', '-185959.3022', '7145450.207', '1777934'], ['5', 'Glasgow', '5', '-473845.2389', '7538620.144', '1209143'], ['6', 'Liverpool', '6', '-340595.1768', '7063197.083', '864122'], ['7', 'South Hampshire', '7', '-174443.8647', '6589419.084', '855569'], ['8', 'Tyneside', '8', '-187604.3647', '7356018.207', '774891'], ['9', 'Nottingham', '9', '-131672.2399', '6979298.895', '729977'], ['10', 'Sheffield', '10', '-163545.3257', '7055177.403', '685368']]


# Functions

Everything we do form here on out will be modelled on the code that we've just finished, so if you get lost you can always come back to this step and start over! Sometimes, you can tie yourself in knots thinking about a problem and it ends up being easier to throw everything out and start again with a simpler approach or new angle...

We can write functions in much the same way that we developed the code above: incrementally. Rather than just sitting down, typing out your function, and hoping for the best, it's often easier to write the code first and _then_ turn it into a function! Let's try this for the code we've written so far by creating a function that will access _any_ URL and return a 'simple' list-of-lists that represents any CSV data stored at the URL's location. 

### Designing a function

The first stage in writing a function is to figure out what inputs and outputs it should have. For this function that is fairly straightforward:
* We give the function a URL that we want to it read in
* The function gives us back a list-of-lists containing the CSV data

We should also give it a name that is fairly obvious to anyone else who comes along and tries to read our code; how about: `readRemoteCSV`?

### Creating  a function

This is a good point to hit Google or StackOverflow for some help. We're trying to `write a function in Python` so why not search for that? I quickly found some useful ones from sites like TutorialPoint and the Python documentation.

I've created the sketch of a function below but have left out quite a bit that you'll have to fill in by searching on your own.

In [18]:
def readRemoteCSV(url):
    """
    Reads a remote CSV file and returns
    a list-of-lists containing the data.
    """
    urlData = [] # Somewhere to store the data

    response = urllib2.urlopen(url) # ???
    for line in response: 
        urlData.append( line.rstrip().split(",") ) # ???
        
    return urlData # ???

print "URL 1:\n"
data1 = readRemoteCSV("http://www.reades.com/CitiesWithWikipediaData-simple.csv")
print data1

# Now...

print "URL 2:\n"
data2 = readRemoteCSV("http://www.reades.com/CitiesWithWikipediaData.csv")
print data2


URL 1:

[['id', 'Name', 'Rank', 'Longitude', 'Latitude', 'Population'], ['1', 'Greater London', '1', '-18162.92767', '6711153.709', '9787426'], ['2', 'Greater Manchester', '2', '-251761.802', '7073067.458', '2553379'], ['3', 'West Midlands', '3', '-210635.2396', '6878950.083', '2440986'], ['4', 'West Yorkshire', '4', '-185959.3022', '7145450.207', '1777934'], ['5', 'Glasgow', '5', '-473845.2389', '7538620.144', '1209143'], ['6', 'Liverpool', '6', '-340595.1768', '7063197.083', '864122'], ['7', 'South Hampshire', '7', '-174443.8647', '6589419.084', '855569'], ['8', 'Tyneside', '8', '-187604.3647', '7356018.207', '774891'], ['9', 'Nottingham', '9', '-131672.2399', '6979298.895', '729977'], ['10', 'Sheffield', '10', '-163545.3257', '7055177.403', '685368']]
URL 2:

[['id', 'Name', 'Rank', 'Longitude', 'Latitude', 'Population', 'Area', 'Density', 'Subs', 'MetroArea', 'Changes'], ['1', 'Greater London', '1', '-18162.92767', '6711153.709', '9787426', '1737.9', '5630', '"London Boroughs', ' H

### Review!

OK, let's just take a look at that again: do you see how, by packaging up the code as a function, we have made it more useful and more re-usable? We now have a little snippet of code that we can _call_ to process _any_ valid URL. So we called `readRemoteCSV` once to read the 'Cities-simple.csv' file, and again to read to the much larger 'Cities.csv' file. We could read 1,000 other URLs using the same function! Now our code is a lot cleaner because we don't need to keep reading lines of code about calling remote files and parsing them; and it's also a lot easier to maintain because if we want to _change_ the way that we parse remote CSV files then we only need to do it in _one place_ and then everywhere that we use this function benefits form the improvement... which is what we're going to do now.

## Calculating the Mean

I'd like you to write a function that will enable you to calculate the mean city size of data retrieved from _any_ URL. So you should be able to call _one_ function that will work for both `Cities.csv` and `Cities-simple.csv`. You'll need to look closely at how the two files are 'laid out': where is the population column, and how would be iterate over the rows to find the mean?

### Designing the Function

OK, we know that `readRemoteCSV` will give us back a list-of-lists: the 'big list' contains a large number of 'small lists', each of which represents a row in the data set. Let's break this down:
* We know that we will have a LoL (List-of-Lists) to work from
* We know that each 'small list' represents a row in the data
* We know that the position of the column of interest might change from data set to data set
* We know that we'll need to convert every value to a... `float`? `int`? Let's assume `float`.
* We know that we'll need to sum up the values
* We know that we'll need to keep track of how many rows of data there are

As before, let's start by working it out _as code_, and then package it up _as a function_ once it's working.

In [19]:
# The starting point...
for row in data1:
    print row

['id', 'Name', 'Rank', 'Longitude', 'Latitude', 'Population']
['1', 'Greater London', '1', '-18162.92767', '6711153.709', '9787426']
['2', 'Greater Manchester', '2', '-251761.802', '7073067.458', '2553379']
['3', 'West Midlands', '3', '-210635.2396', '6878950.083', '2440986']
['4', 'West Yorkshire', '4', '-185959.3022', '7145450.207', '1777934']
['5', 'Glasgow', '5', '-473845.2389', '7538620.144', '1209143']
['6', 'Liverpool', '6', '-340595.1768', '7063197.083', '864122']
['7', 'South Hampshire', '7', '-174443.8647', '6589419.084', '855569']
['8', 'Tyneside', '8', '-187604.3647', '7356018.207', '774891']
['9', 'Nottingham', '9', '-131672.2399', '6979298.895', '729977']
['10', 'Sheffield', '10', '-163545.3257', '7055177.403', '685368']


In [20]:
# Now let's track a particular column
col = 3
for row in data1:
    print row[col] # ???

Longitude
-18162.92767
-251761.802
-210635.2396
-185959.3022
-473845.2389
-340595.1768
-174443.8647
-187604.3647
-131672.2399
-163545.3257


In [21]:
# And now let's figure out the mean
col   = 3
total = 0 # What's the sum of the values?
count = 0 # How many values have we read?
for row in data1:
    print row[col]
    value = row[col]
    count += 1
    total += value

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

Ooops, that last one didn't work so well. How would you fix this?

Here are _two_ hints:
1. What is the count when you are reading the first row (which contains the column name)?
2. If the value is a string, how do you convert it to an int

_P.S._ I also broke one very important thing deliberately

In [36]:
# And now let's figure out the mean
col   = 5
total = 0.0 # What's the sum of the values?
count = 0   # How many values have we read?
for row in data1:
    print(row[col])
    if count == 0: # ???
        count += 1
    else: 
        value = float(row[col]) # ???
        count += 1
        total += total


print total/count

Population
9787426
2553379
2440986
1777934
1209143
864122
855569
774891
729977
685368
0.0


OK, we're almost there now: we know _how_ to calculate the mean for any column that is numeric (dealing with non-numeric columns would be nice but it's just adding extra difficulty to this notebook). Now we want to package this up as a function so that you can just write `calcMean(...)` and get back an answer!

Here's a skeleton to get you started:

In [38]:
def calcMean(data, col):
    "Take a list-of-lists and derive the mean for a specified column."
    total = 0.0
    count = 0
    
    for row in data:
        # print(row[col]) # Uncomment to debug
        if count == 0: # ???
            count += 1
        else: 
            value = float(row[col]) # ???
            count += 1
            total += value
    
    return total/count

data1 = readRemoteCSV("http://www.reades.com/CitiesWithWikipediaData-simple.csv")
print "Mean of simple file populations is: " + str(calcMean(data1,5))

# Now...

data2 = readRemoteCSV("http://www.reades.com/CitiesWithWikipediaData.csv")
print "Mean of big file populations is: " + str(calcMean(data2,5))

Population
9787426
2553379
2440986
1777934
1209143
864122
855569
774891
729977
685368
Mean of simple file populations is: 1970799.54545


And there you go! Done.

You've written two functions: one to read a remote file from a URL, and one to calculate the mean for a simple CSV file of _any_ size. I hope you'll agree that that is pretty handy, but that it's also pretty awkward: we're not doing any type-checking (to see if something is an integer, float, or string) and if we get it wrong the whole thing 'blows up' on us. It's also just kind of _inelegant_ since we have all of these counters (`total` and `count`) to keep track of things... is this what's really going on behind the scenes?

# Thinking About Data

I've said before that the way a computer 'thinks' and the way that we think doesn't always line up naturally. Experienced programmers can think their way _around_ a problem by working _with_ the computer, rather than against it. Let's apply this approach to the parsing of CSV files.

## What's an _Appropriate_ Data Structure?

As you saw when I asked you to calculate the mean population of British cities twice – once using the simple file, and once using the bigger, more complex file – there is a 'problem': our list-of-lists isn't very easy to navigate. Not only _might_ the location of the Population column be different in the two files (as it was, deliberately), but when we want to work out the mean we need to step through a lot of irrelevant data as well (we need to skip past the name, latitude, longitude, etc.). And if I asked you to find the _largest_ city you'd need to do even more work.

So how does the experienced programmer get around this? 'Simple': she realises that the data is organised the wrong way! We humans naturally tend to think in rows of data: London has the following _attributes_ (population, location, etc.), and York has a different set of attributes. Se we read across the row because that's the easiest way for us to read it.

But a computer doesn't have to work that way. For a computer, it's as easy to read _down_ a column as it is to read _across_ a row. In fact, it's easier, because each column has a different _type_ of data: so one column contains names (strings), another column contains population (integers), and other columns contain other types of data (floats, etc.). Better still, the order of the columns often doesn't matter as long as we know what they are called: it's easier to ask for the 'population column' than it is to ask for the 6th column since, for all we know, the population column might be in a different place.

## A Dictionary of Lists

So if we don't mind about column order, only row order (so that we can still link up all of the London data) then a dictionary of lists would be a nice way to handle things. Let's talk this out a bit with some example code, but first, here are the first four rows of data from the simple file:

```python
['id', 'Name', 'Rank', 'Longitude', 'Latitude', 'Population'], 
['1', 'Greater London', '1', '-18162.92767', '6711153.709', '9787426'], 
['2', 'Greater Manchester', '2', '-251761.802', '7073067.458', '2553379'], 
['3', 'West Midlands', '3', '-210635.2396', '6878950.083', '2440986']
```

Here's how it would look as a dictionary of lists organised by _column_, not by row:

```python
myData = {
    'id'         : [1, 2, 3],
    'Name'       : ['London', 'Manchester', 'West Midlands'],
    'Rank'       : [1, 2, 3],
    'Longitude'  : [-18162.92767, -251761.802, -210635.2396],
    'Latitude'   : [6711153.709, 7073067.458, 6878950.083],
    'Population' : [9787426, 2553379, 2440986],
}

```

What does this do better? Well, for starters, we know that everything in the 'Name' column will be a string, and that everything in the 'Longitude' column is a float, while the 'Population' column contains integers. So that's made life easier already. But let's test this out and see how it works.

In [17]:
myData = {
    'Name'       : ['London','Manchester','West Midlands'],
    'Rank'       : [1, 2, 3, 4],
    'Longitude'  : [-18162.92767, -251761.802, -210635.2396],
    'Latitude'   : [6711153.709, 7073067.458, 6878950.083],
    'Population' : [9787426, 2553379, 2440986],
}

# Find the population of Manchester
pop = myData['Population'][myData['Name'].index('Manchester')]
print "The population of Manchester is: " + str(pop)

# Find the westernmost city
city = myData['Name'][myData['Longitude'].index(max(myData['Longitude']))]
print "The westernmost city is: " + str(city)

# Find the mean population of the cities
import numpy as np # Need to import a useful package
mean = np.mean(myData['Population'])
print "The mean population is: " + str(mean)

The population of Manchester is: 2553379
The westernmost city is: London
The mean population is: 4927263.66667


## Review!

There's a _lot_ of content to process in the code above, so do _not_ rush blindly on if this is confusing. Stop. Think it through. We'll go through each one in turn, but they nearly all work in the same way.

### The Population of Manchester

The code can look pretty daunting, so let's break it down into two parts.

What would you get if you ran just this code?
```python
myData['Population'][0]
```
Remember that this is a dictionary-of-lists (DoL). So, Python first looks for a key named `Population` in the myData dictionary. It finds out that the value associated with this key is a _list_ (`[9787426, 2553379, 2440986]`). And this example, it just pulls out the first value (index 0), which is `9787426`. Does that make sense?

Now, to the second part:
```python
myData['Name'].index('Manchester')

```
This is very similar: we look in the dictionary for the key `Name` and find that that's _also_ a list (`['London','Manchester','West Midlands']`, since you asked). If you don't remember what `index` does, don't worry, here's the output from Python's `help()` function:
```
Help on built-in function index:

index(...)
    L.index(value, [start, [stop]]) -> integer -- return first index of value.
    Raises ValueError if the value is not present.
```
So all we're doing is asking Python to find out the index of 'Manchester' in the list associated with the dictionary key 'Name' _instead_ of just sticking in a `0` to get the first index value. Putting these two things back together what we're doing is:
* Finding the index of 'Manchester' in the Name column,
* Using that index to read a value out of the Population column.

Does that make sense? If it does then you should be having a kind of an Alice-through-the-Looking-Glass moment.

### The Westernmost City

Where this approach really comes into its own is on problems that involve maths. To figure out the westernmost city in this list we need to find the _maximum_ Longitude and then use _that_ to look up the right city. So let's do the same process of pulling this appart into two steps:

It should be _pretty_ obvious what this does:
```python
myData['Name'][0]
```
But we don't just want the first city in the list, we want the one with the highest longitude. So to achieve that we need to replace the `0` with an index that we found by looking in the `Longitude` list.
```python
myData['Longitude'].index(max(myData['Longitude']))

```
Ugh, that's still a little hard to read, isn't it? Let's break it down differently:

```python
myData['Longitude'].index(
    max(myData['Longitude'])
)

```
There's the same `.index` which tells us that Python is going to look for something in the list associated with the `Longitude` key. All we've done is change what's _inside_ that index function: `max(myData['Longitude'])` is telling Python to find the _maximum_ value in the `myData['Longitude']` list. So to explain this in three steps, what we're doing is:
* Finding the maximum value in the Longitude column (we know the value, we don't know where it is!),
* Finding the index (position) of that value in the Longitude column (now we know where it is!),
* Using that index to read a value out of the Name column.

I am a nerd, but that's pretty cool, right? In one line of code we managed to quickly find out where the data we needed was even though it involved three discrete steps. Remember how much work it was to find the mean when you were still thinking in _rows_, not _columns_?

### The Average City Size

Yeah, let's try that too.

Here we're going to 'cheat' a little bit: rather than writing our own function, we're going to import a package and use someone _else's_ function. The `numpy` package contains a _lot_ of useful functions that we can call on (if you don't believe me, add `dir(np)` after the `import` statement), and one of them calculates the average of a list or array of data.
```python
import numpy as np # Need to import a useful package
mean = np.mean(myData['Population'])
```
This is where our new approach really comes into its own: because all of the data in that _series_ (i.e. column) is in one place, we can just throw the whole thing into the `np.mean` function rather than hyaving to use all of those convoluted loops and counters. Simples, right?

### Standard Devision

By using `numpy` can you figure out how to modify the code above to look at the standard deviation instead of the mean? You might need a refresher as to how to calculate the standard deviation: http://www.mathsisfun.com/data/standard-deviation.html

## Review!

So the _really_ clever bit in all of this isn't switching from a list-of-lists to a dictionary-of-lists, it's recognising that the latter is a _better_ way to work _with_ the data that we're trying to analyse and that that there are useful functions that we can exploit to do the heavy lifting for us. Simply be changing the way that we stored the data in a 'data structure' (i.e. complex arrangement of lists, dictionaries, and variables) we were able to do away with lots of for loops and counters and conditions, and reduce many difficult operations to something that could be done on one line! 

# Formatting a Number

A final, handy trick if you want to output numbers in a _pretty_ way is to understand how the `format` method associated with string objects works: different cultures format numbers differently, so the English use commas as the thousands separator and a full-stop as the decimal separator but the French, naturally, do it their own way.

Here's an example:

In [72]:
print "{:,.2f}".format(mean)

import locale
locale.setlocale(locale.LC_ALL, 'fr_FR')
print locale.format('%0.2f', mean, grouping=True, monetary=True)

4,927,263.67
4 927 263,67


Unfortunately, most programming languages were written by Anglophones and so most applications will happily output Anglo-formatted numbers but are rather less happy doing anyone else's.

More on `format` in the _Python String Format Cookbook_: https://mkaz.tech/python-string-format.html